-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 
-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력하는 SQL문
-- 카테고리명을 기존으로 오름차순 정렬
SELECT b.CATEGORY, SUM(bs.SALES) "TOTAL_SALES"
FROM BOOK b RIGHT JOIN BOOK_SALES bs
    ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;